FROM wordpress:php7.1

# add libraries
# PHPZip
RUN apt-get update && \
    apt-get install -y zlib1g-dev && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-install zip 

WORKDIR /var/www/html