version: "2"

services:

  dbserver:
    image: mysql:latest
    volumes:
      - ./mysqldb:/var/lib/mysql
    ports:
      - "9090:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbdevpass

  wordpress:
    depends_on:
      - dbserver
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    links:
      - dbserver:mysql
    environment:
      WORDPRESS_DB_PASSWORD: dbdevpass
