version: "3"

services:

  dbserver:
    image: mysql:5.5
    volumes:
      - ./mysqldb:/var/lib/mysql
    ports:
      - "9090:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbdevpass

  wordpress:
    depends_on:
      - dbserver
    image: wordpress/pluginlibs
    build:
      context: .
      dockerfile: dockerfile-wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    links:
      - dbserver:mysql
    environment:
      WORDPRESS_DB_PASSWORD: dbdevpass
